name: Build and Push DB Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push: 
    runs-on: ubuntu-latest
    steps:
      # 1. DockerHub 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. Checkout 코드
      - name: Checkout repository
        uses: actions/checkout@v3

      # 3. 이전 이미지 삭제
      - name: Delete old images
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/dailyhubdb || true
          docker rm ${{ secrets.DOCKERHUB_USERNAME }}/dailyhubdb || true
          docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/dailyhubdb || true

      # 4. MySQL Docker 이미지 빌드 및 푸시
      - name: Build MySQL Docker image
        working-directory: dailyhubdb
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dailyhubdb .
          
      - name: Push MySQL Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dailyhubdb
